[package]
name = "scoundrel"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.27"
crossterm = "0.27"
anyhow = "1"
thiserror = "1"
rand = "0.8"
strum = { version = "0.26", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
